- name: change EnableRemoteCommands=0
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: 'EnableRemoteCommands='
    line: 'EnableRemoteCommands=0'

- name: change server
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Server='
    line: '#Server=127.0.0.1'

- name: change StartAgents
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: 'StartAgents='
    line: 'StartAgents=0'

- name: change server active
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: 'ServerActive='
    line: 'ServerActive=192.168.x.x

- name: change hostname
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Hostname='
    line: 'Hostname={{ ansible_hostname }}'

- name: change HostMetadataItem
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    line: 'HostMetadataItem=system.uname'

- name: enable zabbix
  service:
    name: zabbix-agent
    enabled: yes
    state: restarted

- name: restart zabbix
  service:
    name: zabbix-agent
    state: restarted
