- include_tasks: install_zabbix_agent_centos.yml
  when: 
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - uninstall_zabbix_agent == false

- include_tasks: install_zabbix_agent_debian.yml
  when: 
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - uninstall_zabbix_agent == false


- include_tasks: install_zabbix_agent_common_active.yml
  when:
    - uninstall_zabbix_agent == false
    - zabbix_checks_active == true

- include_tasks: install_zabbix_agent_common_passive.yml
  when:
    - uninstall_zabbix_agent == false
    - zabbix_checks_active == false

- include_tasks: uninstall_zabbix_agent.yml
  when: 
    - uninstall_zabbix_agent == true

